
rule manhattan_plot_GAraw:
	'Manhattan plot for GAraw.'
	input:
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_allPTD.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/allPTD.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_manhattan.png'
	script:
		'manhattan_plot.R'

rule effect_origin_lm:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/effect_origin/haplotype_analysis_all.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_lm_h2_maternal.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_lm_h3_maternal.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_lm_h1_maternal.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_lm_legend.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/GAraw_effect_origin_lm.txt'
	script:
		'lm_effect_origin.R'

rule effect_origin_dendrogram:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/effect_origin/haplotype_analysis_all.txt',
                '/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_dend.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_dend_legend.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/GAraw_effect_origin_dend.txt'
	script:
		'effect_origin_dendrogram.R'

rule effect_origin_ternary:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/effect_origin/haplotype_analysis_all.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GAraw_effect_origin_ternary.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/GAraw_effect_origin_ternary.txt'
	script:
		'effect_origin_ternary.R'

rule gene_based_colocalization:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/eqtls/coloc/iPSC/pph_GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/gene_based/fastBAT_GAraw.txt.gene.fastbat',
		'/mnt/hdd/common/pol/metaGWAS/processed_data/UCSC_gene_cds.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/eqtls/coloc/iPSC/results_GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/gene_based_coloc_eqtl.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/gene_based_coloc_eqtl.txt',
		'/mnt/hdd/common/pol/metaGWAS/figures/gene_based_coloc_eqtl_legend.pdf',
		'/mnt/hdd/common/pol/metaGWAS/Tables/Gene_based_eQTL_coloc.txt'
	script:
		'gene_based_vs_coloc_iPSC.R'

rule coloc_BW:
	''
	input:
		expand('/mnt/hdd/common/pol/metaGWAS/colocalization/GAraw/pph_{BW}.txt', BW= ['BW_maternal_effect', 'BW_fetal_effect'])
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/spider_BW_coloc_maternal.png',
		'/mnt/hdd/common/pol/metaGWAS/figures/spider_BW_coloc_fetal.png'
	script:
		'BW_coloc_spider.R'

rule KCNAB1_Phewas:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/KCNAB1/PheWas/PAN_UKBB/pph_GAraw.txt',
                '/mnt/hdd/common/pol/references/PAN_UKBB/PAN_UKBB_manifest.txt',
                '/mnt/hdd/common/pol/metaGWAS/KCNAB1/PheWas/FINNGEN/results/pph_GAraw.txt',
                '/mnt/hdd/common/pol/references/FINNGEN/manifest_R4.txt'
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/KCNAB1_PheWas.tiff',
                '/mnt/hdd/common/pol/metaGWAS/data_figures/KCNAB1_PheWas.txt'
        script:
                'KCNAB1_pheWAS.R'


rule ADCY5_Phewas:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/PAN_UKBB/final/pph.txt',
		'/mnt/hdd/common/pol/references/PAN_UKBB/PAN_UKBB_manifest.txt',
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/FINNGEN/results/pph_GAraw.txt',
		'/mnt/hdd/common/pol/references/FINNGEN/manifest_R4.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_PheWas.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/ADCY5_PheWas.txt'
	script:
		'ADCY5_pheWAS.R'

rule ADCY5_FST_AFR_EUR:
	''
	input:
		'/mnt/hdd/common/pol/references/FST/results/EUR_AFR.weir.fst',
		'/mnt/hdd/common/pol/references/FST/results/EUR_EAS.weir.fst',
		'/mnt/hdd/common/pol/references/FST/results/AFR_EAS.weir.fst',
		'/mnt/hdd/common/pol/metaGWAS/SNPsnap/SNPsnap_ADCY5/matched_snps.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_FST_EUR_AFR.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_FST_EUR_EAS.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_FST_AFR_EAS.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/ADCY5_FST.txt',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/ADCY5_FST_comparison.txt'
	params:
	script:
		'ADCY5_FST_AFR_EUR.R'

rule genet_correlations_BW:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/GAraw_rg_temp',
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/repr_phenos_rg'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/BW_genetic_correlations.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/BW_genetic_correlations.txt'
	script:
		'BW_genetic_correlations.R'


rule genet_correlations_reproductive_traits:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/GAraw_rg_temp',
                '/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/allPTD_rg_temp',
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/mtCOJO/results/BW_maternal_effect_rg_temp'
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_genetic_correlations.tiff',
                '/mnt/hdd/common/pol/metaGWAS/data_figures/repr_pheno_genetic_correlations.txt',
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_genetic_correlations_legend.tiff'
        script:
                'repr_pheno_correlations.R'

rule partitioned_h2_figure:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/LDscore/part_h2/GAraw.results'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/partitioned_h2.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/partitioned_h2.txt'
	script:
		'partitioned_h2.R'

rule MacArthurlab_enrichment:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/enrichment/GNOMAD/pLI_GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/enrichment/MacArthur/diseases_GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/MacArthur_enrichment.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/MacArthur_enrichment.txt'
	script:
		'MacArthurlab_enrichment.R'

rule ADCY5_effect_direction:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/FINNGEN/results/individual_variant_GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/FINNGEN/results/pph_GAraw.txt',
		'/mnt/hdd/common/pol/references/FINNGEN/manifest_R4.txt',
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/PAN_UKBB/final/individual_variant.txt',
		'/mnt/hdd/common/pol/metaGWAS/ADCY5/PheWas/PAN_UKBB/final/pph.txt',
		'/mnt/hdd/common/pol/references/PAN_UKBB/PAN_UKBB_manifest.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_effect_direction.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/ADCY5_effect_direction.txt',
		'/mnt/hdd/common/pol/metaGWAS/figures/ADCY5_effect_direction_legend.pdf'
	script:
		'ADCY5_effect_direction.R'

rule conditional_all:
	''
	input:
		'/mnt/hdd/common/pol/references/approx_LD_blocks.txt',
		'/mnt/hdd/common/pol/metaGWAS/mtCOJO/BW_maternal_effect_GA.mtcojo.cma.gz',
		'/mnt/hdd/common/pol/metaGWAS/mtCOJO/BW_fetal_effect_GA.mtcojo.cma.gz',
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/BW_conditioning.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/BW_conditioning.txt',
		'/mnt/hdd/common/pol/metaGWAS/figures/BW_conditioning2.pdf'
	script:
		'BW_conditioning.R'


rule conditional_BW_top_SEM_classification:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/references/bw_classification.txt',
                '/mnt/hdd/common/pol/metaGWAS/mtCOJO/BW_maternal_effect_GA.mtcojo.cma.gz',
                '/mnt/hdd/common/pol/metaGWAS/mtCOJO/BW_fetal_effect_GA.mtcojo.cma.gz',
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning.tiff',
                '/mnt/hdd/common/pol/metaGWAS/data_figures/top_BW_conditioning.txt',
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning2.pdf'
        script:
                'BW_conditioning_top.R'

rule mediation_individual_SNPs_BW_GA_MoBa:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/mediation/BW_GA_mediation_analysis.txt'
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning_individual.tiff',
                '/mnt/hdd/common/pol/metaGWAS/data_figures/top_BW_conditioning_individual.txt',
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning2_individual.pdf'
        script:
                'mediation_BW_GA_individual_level_data.R'

rule mediation_individual_SNPs_BW_GA_deCODE:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/mediation/Birthweight_own_4Rev_adjSexYob_adjSonar_220905.txt',
		'/mnt/hdd/common/pol/metaGWAS/mediation/Birthweight_mother_1stCh_4Rev_adjSexYobMAge_adjSonar_220905.txt'
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning_individual_decode.tiff',
                '/mnt/hdd/common/pol/metaGWAS/data_figures/top_BW_conditioning_individual_decode.txt',
                '/mnt/hdd/common/pol/metaGWAS/figures/top_BW_conditioning2_individual_decode.pdf'
        script:
                'mediation_BW_GA_individual_level_data_decode.R'

rule MR_GA_BW_haplotype:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/effect_origin/haplotype_analysis_all.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/sumstats/BW_{genome}_effect.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/MR_GA_BW_{genome}_MT.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/MR_GA_BW_{genome}_MnT.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/MR_GA_BW_{genome}_PT.pdf',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/MR_GA_BW_plot_haplotype_{genome}.txt',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/MR_GA_BW_2sampleMR_haplotype_{genome}.txt'
	script:
		'MR_GA_BW_haplotype.R'

rule coloc_repr_phenos:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/colocalization/GAraw/pph_allpheno.txt',
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/GAraw_rg_temp'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_coloc_main.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_coloc_GENE.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_coloc_rg.tiff'
	script:
		'repr_pheno_coloc.R'

rule repr_pheno_LCV:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/GAraw_rg_temp',
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/allPTD_rg_temp',
		'/mnt/hdd/common/pol/metaGWAS/LCV/results/repr_pheno/GAraw_LCV.txt',
		'/mnt/hdd/common/pol/metaGWAS/LCV/results/repr_pheno/allPTD_LCV.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_LCV.pdf',
		'/mnt/hdd/common/pol/metaGWAS/Tables/repr_pheno_LCV.txt'
	script:
		'repr_pheno_LCV.R'

rule repr_pheno_correlations:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/GAraw_rg_temp',
                '/mnt/hdd/common/pol/metaGWAS/repr_phenos/LDSC/results/allPTD_rg_temp'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_rg.tiff',
		'/mnt/hdd/common/pol/metaGWAS/data_figures/repr_pheno_rg.txt',
		'/mnt/hdd/common/pol/metaGWAS/figures/repr_pheno_rg_legend.tiff'
	script:
		'repr_pheno_correlations.R'

rule RNA_enrichment:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/enrichment/HPA/RNA_GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/RNA_enrichment.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/RNA_enrichment_legend.pdf'
	script:
		'RNA_enrichment.R'


### Supp figures


rule QQ_plot:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_{pheno}.txt.gz'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/QQ_plot_{pheno}.png'
	script:
		'QQ_plot.R'
	


rule h2_plots:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/LDscore/h2/h2_all_phenos.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/h2_allpheno.pdf'
	script:
		'h2_allphenos.R'

rule h2_cohorts:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/LDscore/individual_cohorts/h2/allcohorts.txt',
		'/mnt/hdd/common/pol/metaGWAS/LDscore/individual_cohorts/h2/allPTD/allcohorts.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/h2_allcohort.pdf'
	script:
		'h2_cohorts.R'

rule genet_correlations_GAraw:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/LDscore/GAraw_temp'
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/genet_corr_GAraw.pdf'
        script:
                'genet_correlations_meta.R'


rule post_term_manhattan:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_postTerm.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/postTerm.txt',
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/postTerm_manhattan.png'
	script:
		'manhattan_plot_postTerm.R'


rule GAnrm_manhattan:
        ''
        input:
                '/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAnrm.txt.gz',
                '/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/GAnrm.txt',
        output:
                '/mnt/hdd/common/pol/metaGWAS/figures/GAnrm_manhattan.png'
        script:
                'manhattan_plot_postTerm.R'

rule forest_plot_EEFSEC:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/reports/forest/data/top_variants_GAraw.txt',
                '/mnt/hdd/common/pol/metaGWAS/sumstats/META/meta_GAraw_1.txt',
                '/mnt/hdd/common/pol/metaGWAS/topregions/final/GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/{prev_locus}_forest.pdf'
	script:
		'forest_plot_EEFSEC.R'

rule sex_hormones_MR:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/MR/raw_data/formatted_sex_hormones.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/MR/results/GAraw/MR_clusters.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/SHBG_GAraw_2SMR.png',
		'/mnt/hdd/common/pol/metaGWAS/figures/Testosterone_GAraw_2SMR.png'
	script:
		'MR_sex_hormones_GA.R'

rule cell_type_enrichmente:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/LDscore/h2_cts/gene_expr/GAraw.cell_type_results.txt',
		'/mnt/hdd/common/pol/metaGWAS/references/LD_score_categories.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/cell_type_enrichment.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/cell_type_enrichment_legend.pdf'
	script:
		'cell_type_enrichment.R'

rule labor_deg_enrichment:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/LDscore/own_annot/results/all/GAraw_labor_DEGs.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/labor_deg_enrichment_pvalue.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/labor_deg_n_genes_pvalue.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/labor_deg_enrichmente_pvalue_legend.pdf'
	script:
		'labor_deg.R'

rule ternary_coloc_sex_hormones:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/colocalization/SHBG_fem/pph_GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/colocalization/Testosterone_fem/pph_GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/shbg_coloc_GAraw_ternary.tiff',
		'/mnt/hdd/common/pol/metaGWAS/figures/testo_coloc_GAraw_ternary.tiff'
	script:
		'coloc_sex_hormones.R'

rule tile_plot_evo:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/references/all_z_score_pval.tsv',
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/GAraw.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/evo.pdf'
	script:
		'evo.R'

rule PGS_correlations:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/references/GA_BW_PGS_correlations.txt'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GA_BW_PGS_correlations.pdf'
	script:
		'GA_BW_PGS_correlations.R'

rule top_SNPs:
	''
	input:
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/GAraw.txt',
		'/mnt/hdd/common/pol/metaGWAS/topregions/top_variants/allPTD.txt',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_GAraw.txt.gz',
		'/mnt/hdd/common/pol/metaGWAS/sumstats/META/Maternal_GWAMA_allPTD.txt.gz'
	output:
		'/mnt/hdd/common/pol/metaGWAS/figures/GA_PTD_BETA_correlations.pdf',
		'/mnt/hdd/common/pol/metaGWAS/figures/GA_PTD_BETA_correlations_legend.pdf'
	script:
		'GAraw_vs_allPTD.R'
