CHR_nms= ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X']

pheno_nms= ['allPTD', 'GAraw', 'GAnrm', 'postTerm']


include: 'scripts/reports/Snakefile'
include: 'scripts/PGS_BW/Snakefile'
include: 'scripts/effect_origin/Snakefile'
include: 'scripts/PGS_repr_pheno/Snakefile'
include: 'scripts/fetal_SNP/Snakefile'

rule all:
	'Collect all results'
	input:
#		'/mnt/work/pol/metaGWAS/GxE_BW/results/GAraw.txt',
		'/mnt/work/pol/metaGWAS/pheno/trio_pheno.txt',
		'/mnt/work/pol/metaGWAS/effect_origin/results/HUNT.txt',
#		expand('/mnt/work/pol/metaGWAS/to_phase/data/mother_child.{ext}', ext= ['bim', 'bed', 'fam'])
		expand('/mnt/work/pol/metaGWAS/PGS/BW/GRS/BW_{haplo}.txt', haplo= ['MT', 'MnT', 'PT', 'PnT']),
		'/mnt/work/pol/metaGWAS/PGS/BW/pheno/delivery/results/MR_BW_PGS.txt',
		'/mnt/work/pol/metaGWAS/MR/repr_traits/delivery/lh/MR_repr_traits_indiv_level.txt',
		'/mnt/work/pol/metaGWAS/fetal_SNP/results/HUNT.txt'

rule phenofile:
	''
	input:
		'/mnt/archive/hunt/phenotypes/mfr/MFR.txt',
		'/mnt/work/hunt/relatedness/mother_samples_related.kin0',
		'/mnt/work/hunt/pca/mother_pca.sscore'
	output:
		'/mnt/work/pol/metaGWAS/pheno/pheno_all.txt',
		'/mnt/work/pol/metaGWAS/pheno/covars_all.txt'
	script:
		'scripts/pheno_file.R'

rule phenofile_duo:
        ''
        input:
                '/mnt/archive/hunt/phenotypes/mfr/MFR.txt',
                '/mnt/work/hunt/relatedness/all_related.kin0',
                '/mnt/work/hunt/pca/fetal_pca.sscore'
		''
        output:
                '/mnt/work/pol/metaGWAS/pheno/duo_pheno.txt'
        script:
                'scripts/pheno_file.R'

rule phenofile_trio:
	''
	input:
		'/mnt/archive/hunt/phenotypes/mfr/MFR.txt',
		'/mnt/work/hunt/relatedness/all_related.kin0',
		'/mnt/work/hunt/pca/fetal_pca.sscore',
		'/mnt/work/pol/metaGWAS/effect_origin/processed_data/parent_offspring_trios.txt'
	output:
		'/mnt/work/pol/metaGWAS/pheno/trio_pheno.txt'
	script:
		'scripts/pheno_file.R'
