CHR_nms= ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X']

pheno_nms= ['allPTD', 'GAraw', 'GAnrm', 'postTerm']


include: 'scripts/FINEMAP/Snakefile'


rule all:
	'Collect all results'
	input:
		expand('/mnt/work/pol/metaGWAS/FINEMAP/results/{pheno}.{ext}', ext= ['config', 'snp', 'cred', 'log_sss'], pheno= pheno_nms),
		expand('FINEMAP/{pheno}.{ext}', ext= ['config', 'snp', 'cred', 'log_sss'], pheno= pheno_nms),
		'/mnt/work/pol/metaGWAS/processed_data/ids/chrX_IDS.txt'
