import csv
import numpy as np
import gzip
import math

allPTD_coh_nms= ['23andme', 'ALSPAC', 'CHOP', 'DECODE', 'EGCUT', 'NFBC1966',  'MOBAGENETICS', 'DBDS', 'DNBCCASES', 'DNBCCONTROLS', 'DNBCPTD', 'HUNT', 'DILT1DGC', 'WTCCC58BC']


postTerm_coh_nms= ['ALSPAC', 'EGCUT', 'DECODE', 'NFBC1966', 'MOBAGENETICS', 'DBDS', 'DNBCCASES', 'DNBCCONTROLS', 'HUNT', 'DILT1DGC', 'WTCCC58BC']

GAraw_coh_nms= ['23andme', 'ALSPAC', 'CHOP', 'DECODE',  'NFBC1966', 'STORK', 'STORKGROR', 'MOBAGENETICS', 'DBDS',  'DNBCCASES', 'DNBCCONTROLS', 'HUNT', 'DNBCPTD', 'DILT1DGC', 'WTCCC58BC', 'CCHMC', 'GPN']

GAnrm_coh_nms= ['ALSPAC', 'CHOP', 'DECODE', 'NFBC1966', 'STORK', 'STORKGROR', 'MOBAGENETICS', 'DBDS',  'DNBCCASES', 'DNBCCONTROLS', 'HUNT', 'DNBCPTD', 'DILT1DGC', 'WTCCC58BC']

pheno_nms= ['allPTD', 'postTerm', 'GAraw', 'GAnrm']

rule METAL:
    'Inverse-variance weighted meta-analysis.'
    input:
        'scripts/meta/metal_script_allPTD',
        'scripts/meta/metal_script_postTerm',
        'scripts/meta/metal_script_GAraw',
        'scripts/meta/metal_script_GAnrm',
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/allPTD/{allPTD_coh}_allPTD.txt', allPTD_coh= allPTD_coh_nms),
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/postTerm/{postTerm_coh}_postTerm.txt', postTerm_coh= postTerm_coh_nms),
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAraw/{GAraw_coh}_GAraw.txt', GAraw_coh= GAraw_coh_nms),
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAnrm/{GAnrm_coh}_GAnrm.txt', GAnrm_coh= GAnrm_coh_nms)
    output:
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/meta_allPTD_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/meta_postTerm_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/meta_GAraw_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/meta_GAnrm_1.txt',
	'/mnt/hdd/common/pol/metaGWAS/sumstats/META/log/METAL_log.txt'
    shell:
        '''
        /home/pol/software/generic-metal/metal {input[0]} >> {output[4]}
        /home/pol/software/generic-metal/metal {input[1]} >> {output[4]}
        /home/pol/software/generic-metal/metal {input[2]} >> {output[4]}
        /home/pol/software/generic-metal/metal {input[3]} >> {output[4]}
        '''

rule METAL_noMOBA:
    'Inverse-variance weighted meta-analysis without MOBA samples.'
    input:
        'scripts/meta/noMOBA_metal_script_GAraw',
        'scripts/meta/noMOBA_metal_script_GAnrm',
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAraw/{GAraw_coh}_GAraw.txt', GAraw_coh= GAraw_coh_nms),
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAnrm/{GAnrm_coh}_GAnrm.txt', GAnrm_coh= GAnrm_coh_nms)
    output:
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NOMOBA/meta_GAraw_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NOMOBA/meta_GAnrm_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NOMOBA/log/METAL_log.txt'
    shell:
        '''
        /home/pol/software/generic-metal/metal {input[0]} >> {output[2]}
        /home/pol/software/generic-metal/metal {input[1]} >> {output[2]}
        '''

rule METAL_no23andme:
    'Inverse-variance weighted meta-analysis without 23andme samples.'
    input:
        'scripts/meta/no23andme_metal_script_allPTD',
        'scripts/meta/no23andme_metal_script_GAraw',
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAraw/{GAraw_coh}_GAraw.txt', GAraw_coh= GAraw_coh_nms),
        expand('/mnt/hdd/common/pol/metaGWAS/sumstats/GAnrm/{GAnrm_coh}_GAnrm.txt', GAnrm_coh= GAnrm_coh_nms)
    output:
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NO23andme/meta_allPTD_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NO23andme/meta_GAraw_1.txt',
        '/mnt/hdd/common/pol/metaGWAS/sumstats/META/other_meta/NO23andme/log/METAL_log.txt'
    shell:
        '''
        /home/pol/software/generic-metal/metal {input[0]} >> {output[2]}
        /home/pol/software/generic-metal/metal {input[1]} >> {output[2]}
        '''
